### ISSUE TITLE
downloading network diagram PNG fails

### ISSUE THREAD

**Issue by afeld** [18F/cg-diagrams#11]
Steps to reproduce:
1. Visit https://diagrams.fr.cloud.gov/10-1-network.html.
2. Click "Save as PNG".
3. See a "Failed - Network error".

Weirdly, all of the other diagram PNGs download fine.

**Comment by LinuxBozo** [comment]
I think this may be because it's hitting the limit for the amount of information in a data-uri. The javascript that does this basically turns the svg into a data-uri, that then can be placed onto a canvas element which creates the png.

**Comment by afeld** [comment]
Heh, yet _another_ compelling reason for https://github.com/18F/cg-diagrams/issues/13 ... this was just mermaid/scuttle forcing us to keep the diagrams small. Thanks mermaid/scuttle! :trollface:

**Comment by brittag** [comment]
This no longer fails, probably since the diagram is a bit smaller now!
