### ISSUE TITLE
simplify the Network diagram

### ISSUE THREAD

**Issue by afeld** [18F/cg-diagrams#13]
Broken out from https://github.com/18F/cg-product/issues/337.
## Acceptance criteria
- [ ] The graph is legible in one (large) screen

**Comment by mogul** [comment]
@afeld  Can we close this now?

**Comment by afeld** [comment]
No, we had to undo it unfortunately—see https://github.com/18F/cg-diagrams/commit/de3ef1840d5edecb97df8df090feb4651bbd2432.

**Comment by mogul** [comment]
@afeld is this partially done? not yet started? It's listed as `In Progress` and we want to be real about it. Based on the referenced commit I'm guessing the state is "revisit this when we can safely iterate the diagram and SSP references to it at the same time"?

**Comment by afeld** [comment]
Correct. Moved it to the Icebox.
