### ISSUE TITLE
All lines should have labels

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-diagrams#20]
Some lines include labels with a white background to describe what kind of information is flowing. _Should all lines include these kinds of labels?_

// cc @LinuxBozo

**Comment by LinuxBozo** [comment]
I took the approach of using labels where it wasn't obvious what the data was.. For instance, it's pretty obvious that a flow toward a component of `email` is, well, an email.

**Comment by brittag** [comment]
This is definitely up to our good judgment (we don't need to include totally obvious things), but I suggest adding labels when in doubt - since when people are new to learning about a complex system, seeing a label that is obvious can reassure the viewer that the system works as they expect. :D
