### ISSUE TITLE
simplify Monitoring diagram

### ISSUE THREAD

**Issue by afeld** [18F/cg-diagrams#25]
Right now, the Monitoring diagram is very complex...should be easier to understand what's going on at a glance. Ideas:
- Break the notifications section out to its own diagram
- Simplify the labels
## Acceptance criteria
- [ ] The Monitoring diagrams is legible on a single screen

**Comment by brittag** [comment]
Hmm, looking at it, it's somewhat big and rangy, but the path from monitoring components -> alerting/notifications comes up a lot in the SSP, so I'd be inclined to keep this diagram in one piece to help people confidently understand that path.
