### ISSUE TITLE
Diagrams for PRs should be viewable during review

### ISSUE THREAD

**Issue by cnelson** [18F/cg-diagrams#49]
When reviewing a PR the diagrams should be available for review along with the changes to the underlying code.

**Possible Implementation Sketch**
- Concourse monitors for pull requests
- Concourse generates diagrams for each PR and pushes to an s3 bucket
  - s3 bucket has a lifecycle policy to automatically nuke old content
- Concourse updates PR with a link to the generated diagrams as a status check

**Comment by afeld** [comment]
This might be a good opportunity to (start to) think about per-branch deployments more broadly. @jseppi Was there an issue around that somewhere?

**Comment by jseppi** [comment]
@afeld: no, we don't have an issue about doing that. I don't think we (the CALC project) have enough cloud.gov quota to seriously consider doing it for all branches, though I could see doing it with `develop`, `staging`, and `master` branches.

**Comment by jmcarp** [comment]
Can I interest you in https://github.com/jmcarp/cf-review-app?
