### ISSUE TITLE
add boilerplate 18F files

### ISSUE THREAD

**Issue by afeld** [18F/cg-diagrams#6]
https://github.com/18F/open-source-policy/blob/master/practice.md#how-to-license-18f-repos

Not sure how that should interact with the MIT license...?

/cc @rogeruiz

**Comment by rogeruiz** [comment]
I'm comfortable with adding `18F` files. Not sure how we should include the reference to have the original license included. ¯\\_(ツ)_/¯
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by brittag** [comment]
I'll make a PR for this! Here's how we worked it out for a different forked project - https://github.com/18F/retext-18f/blob/master/LICENSE.md

**Comment by afeld** [comment]
Fixed by #19.
